services:
  api:
    image: team-roster-api
    environment:
      - SERVER_PORT=9001
      - FUSIONAUTH_PORT=9011
      - FUSIONAUTH_SERVERNAME=localhost
      - FUSIONAUTH_SERVERNAME_FOR_TOKEN=host.docker.internal
      - CLIENT_ID=1d3c2af4-381a-4c25-b1a7-1d472d411a4d
      - CLIENT_SECRET=TUCWyrRLUag2oGc4WzB5h5abGJ-E8A9IvLL9d9Hujlw
      - REDIRECT_URI=http://localhost:9001/oauth-callback
      - APPLICATION_ID=e6ba1ed7-e4d0-4b6a-83a5-fff95cc8cf6f
      - API_KEY=twhH1MQnhtkmQ3EKxllJqWZy2dnWNGqGrgPd1vutjUC3QjY6a_qrdhr0
      - FRONT_APP_ROOT_URL=http://localhost:5174/loginin
      - TENANT_ID=608525b2-902a-0293-d1f5-d34ad233f74a
    ports:
      - 9001:9001
  front:
    image: team-roster-front
    ports:
      - 5174:80
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=team_roster
      - MYSQL_USER=team_roster
      - MYSQL_PASSWORD=team_roster
